##############################################
# Processing Endpoints
##############################################

### Send video request
POST http://localhost:8000/api/v1/processing/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="video"; filename="REC6766379630202934727.mp4"
Content-Type: video/mp4

< C:/Users/matke/Videos/testVideo11.mp4
--WebAppBoundary--

### Video Processing status
GET http://localhost:8000/api/v1/processing/status/13

### Analyze video
POST http://localhost:8000/api/v1/analysis/analyze?recording-id=13
Content-Type: application/json

{
  "arm_movement": true,
  "eye_contact": true,
  "pitch": true,
  "volume": true,
  "hip": true,
  "filler_words": true
}
### Video Processing - Extract pose landmarks from video
POST http://localhost:8001/api/v1/video/1/analyze/

### Audio Processing - Extract, normalize, and resample audio
POST http://localhost:8004/api/v1/audio/8/analyze/

### Transcript Processing MS - Health Check
# @timeout 60 m
POST http://localhost:8009/api/v1/13/transcribe/

###############################################
# Health Checks
###############################################

### Video Processing MS - Health Check
GET http://localhost:8001/api/v1/health

### Arm Movement Analysis MS - Health Check
GET http://localhost:8002/api/v1/health/

### Eye Contact Analysis MS - Health Check
GET http://localhost:8003/api/v1/health

### Audio Processing MS - Health Check
GET http://localhost:8004/api/v1/health/

### Pitch Analysis MS - Health Check
GET http://localhost:8005/api/v1/health/

### Volume Analysis MS - Health Check
GET http://localhost:8006/api/v1/health/

### Hip Analysis MS - Health Check
GET http://localhost:8007/api/v1/health/

### Transcript Processing MS - Health Check
GET http://localhost:8009/api/v1/health/

###############################################
# Analysis Endpoints
###############################################

### Pitch Analysis - Analyze pitch from processed audio
POST http://localhost:8005/api/v1/pitch/5/analyze/

### Pitch Timeseries - Get pitch timeseries data
GET http://localhost:8005/api/v1/pitch/5/timeseries/

### Volume Analysis - Analyze volume from processed audio
POST http://localhost:8006/api/v1/volume/5/analyze/

### Arm Movement Analysis - Analyze wrist kinematics and gestures
POST http://localhost:8002/api/v1/analyze/arm-movements/49/

### Eye Contact Analysis - Analyze gaze patterns
POST http://localhost:8003/api/v1/eye-contact/47/analyze/

### Hip Analysis - Analyze hip movement and sway
POST http://localhost:8007/api/v1/hip/49/analyze/

### Filler Words Analysis - Analyze filler words
POST http://localhost:8008/api/v1/filler-words/5/analyze/

### Performance - Analyze users performance
POST http://localhost:8012/api/v1/performance/
Content-Type: application/json

{}