### Send video request
POST http://localhost:8000/api/v1/videos/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="video"; filename="REC6766379630202934727.mp4"
Content-Type: video/mp4

< C:/Users/matke/Videos/REC6766379630202934727.mp4
--WebAppBoundary--

### Video analysis microservice health check
GET http://localhost:8001/api/v1/health

### Hand movement analysis microservice health check
GET http://localhost:8002/api/v1/health/

### Eye analysis microservice health check
GET http://localhost:8003/api/v1/health

### Video analysis
POST http://localhost:8001/api/v1/analyze/video/4/

### Hand movement analysis
POST http://localhost:8002/api/v1/analyze/arm-movements/3/

### Eye anaysis
POST http://localhost:8003/api/v1/analyze/eye-contact/4/