import 'package:fluent/config/typography.dart';
import 'package:flutter/material.dart';

class MaterialTheme {
  const MaterialTheme();

  static ColorScheme lightScheme() => const ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xff2b6a46),
    surfaceTint: Color(0xff2b6a46),
    onPrimary: Color(0xffffffff),
    primaryContainer: Color(0xffaff1c4),
    onPrimaryContainer: Color(0xff0d5130),
    secondary: Color(0xff3f5f90),
    onSecondary: Color(0xffffffff),
    secondaryContainer: Color(0xffd5e3ff),
    onSecondaryContainer: Color(0xff254777),
    tertiary: Color(0xff656015),
    onTertiary: Color(0xffffffff),
    tertiaryContainer: Color(0xffece68d),
    onTertiaryContainer: Color(0xff4c4800),
    error: Color(0xff904b3f),
    onError: Color(0xffffffff),
    errorContainer: Color(0xffffdad4),
    onErrorContainer: Color(0xff73342a),
    surface: Color(0xfff6fbf3),
    onSurface: Color(0xff181d19),
    onSurfaceVariant: Color(0xff414942),
    outline: Color(0xff717971),
    outlineVariant: Color(0xffc0c9c0),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xff2c322d),
    inversePrimary: Color(0xff94d5a9),
    primaryFixed: Color(0xffaff1c4),
    onPrimaryFixed: Color(0xff00210f),
    primaryFixedDim: Color(0xff94d5a9),
    onPrimaryFixedVariant: Color(0xff0d5130),
    secondaryFixed: Color(0xffd5e3ff),
    onSecondaryFixed: Color(0xff001b3c),
    secondaryFixedDim: Color(0xffa8c8ff),
    onSecondaryFixedVariant: Color(0xff254777),
    tertiaryFixed: Color(0xffece68d),
    onTertiaryFixed: Color(0xff1e1c00),
    tertiaryFixedDim: Color(0xffd0ca74),
    onTertiaryFixedVariant: Color(0xff4c4800),
    surfaceDim: Color(0xffd6dbd4),
    surfaceBright: Color(0xfff6fbf3),
    surfaceContainerLowest: Color(0xffffffff),
    surfaceContainerLow: Color(0xfff0f5ee),
    surfaceContainer: Color(0xffeaefe8),
    surfaceContainerHigh: Color(0xffe5eae2),
    surfaceContainerHighest: Color(0xffdfe4dd),
  );

  ThemeData light() => theme(lightScheme());

  static ColorScheme lightMediumContrastScheme() => const ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xff003f22),
    surfaceTint: Color(0xff2b6a46),
    onPrimary: Color(0xffffffff),
    primaryContainer: Color(0xff3b7954),
    onPrimaryContainer: Color(0xffffffff),
    secondary: Color(0xff103665),
    onSecondary: Color(0xffffffff),
    secondaryContainer: Color(0xff4e6ea0),
    onSecondaryContainer: Color(0xffffffff),
    tertiary: Color(0xff3a3800),
    onTertiary: Color(0xffffffff),
    tertiaryContainer: Color(0xff746f24),
    onTertiaryContainer: Color(0xffffffff),
    error: Color(0xff5e241b),
    onError: Color(0xffffffff),
    errorContainer: Color(0xffa1594d),
    onErrorContainer: Color(0xffffffff),
    surface: Color(0xfff6fbf3),
    onSurface: Color(0xff0d120e),
    onSurfaceVariant: Color(0xff303832),
    outline: Color(0xff4c544d),
    outlineVariant: Color(0xff676f68),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xff2c322d),
    inversePrimary: Color(0xff94d5a9),
    primaryFixed: Color(0xff3b7954),
    onPrimaryFixed: Color(0xffffffff),
    primaryFixedDim: Color(0xff20603d),
    onPrimaryFixedVariant: Color(0xffffffff),
    secondaryFixed: Color(0xff4e6ea0),
    onSecondaryFixed: Color(0xffffffff),
    secondaryFixedDim: Color(0xff355586),
    onSecondaryFixedVariant: Color(0xffffffff),
    tertiaryFixed: Color(0xff746f24),
    onTertiaryFixed: Color(0xffffffff),
    tertiaryFixedDim: Color(0xff5b570a),
    onTertiaryFixedVariant: Color(0xffffffff),
    surfaceDim: Color(0xffc3c8c1),
    surfaceBright: Color(0xfff6fbf3),
    surfaceContainerLowest: Color(0xffffffff),
    surfaceContainerLow: Color(0xfff0f5ee),
    surfaceContainer: Color(0xffe5eae2),
    surfaceContainerHigh: Color(0xffd9ded7),
    surfaceContainerHighest: Color(0xffced3cc),
  );

  ThemeData lightMediumContrast() => theme(lightMediumContrastScheme());

  static ColorScheme lightHighContrastScheme() => const ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xff00341b),
    surfaceTint: Color(0xff2b6a46),
    onPrimary: Color(0xffffffff),
    primaryContainer: Color(0xff115432),
    onPrimaryContainer: Color(0xffffffff),
    secondary: Color(0xff002c5a),
    onSecondary: Color(0xffffffff),
    secondaryContainer: Color(0xff284a79),
    onSecondaryContainer: Color(0xffffffff),
    tertiary: Color(0xff302d00),
    onTertiary: Color(0xffffffff),
    tertiaryContainer: Color(0xff4f4b00),
    onTertiaryContainer: Color(0xffffffff),
    error: Color(0xff511a12),
    onError: Color(0xffffffff),
    errorContainer: Color(0xff76362c),
    onErrorContainer: Color(0xffffffff),
    surface: Color(0xfff6fbf3),
    onSurface: Color(0xff000000),
    onSurfaceVariant: Color(0xff000000),
    outline: Color(0xff262e28),
    outlineVariant: Color(0xff434b44),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xff2c322d),
    inversePrimary: Color(0xff94d5a9),
    primaryFixed: Color(0xff115432),
    onPrimaryFixed: Color(0xffffffff),
    primaryFixedDim: Color(0xff003b20),
    onPrimaryFixedVariant: Color(0xffffffff),
    secondaryFixed: Color(0xff284a79),
    onSecondaryFixed: Color(0xffffffff),
    secondaryFixedDim: Color(0xff0a3361),
    onSecondaryFixedVariant: Color(0xffffffff),
    tertiaryFixed: Color(0xff4f4b00),
    onTertiaryFixed: Color(0xffffffff),
    tertiaryFixedDim: Color(0xff373400),
    onTertiaryFixedVariant: Color(0xffffffff),
    surfaceDim: Color(0xffb5bab4),
    surfaceBright: Color(0xfff6fbf3),
    surfaceContainerLowest: Color(0xffffffff),
    surfaceContainerLow: Color(0xffedf2eb),
    surfaceContainer: Color(0xffdfe4dd),
    surfaceContainerHigh: Color(0xffd1d6cf),
    surfaceContainerHighest: Color(0xffc3c8c1),
  );

  ThemeData lightHighContrast() => theme(lightHighContrastScheme());

  static ColorScheme darkScheme() => const ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xff94d5a9),
    surfaceTint: Color(0xff94d5a9),
    onPrimary: Color(0xff00391e),
    primaryContainer: Color(0xff0d5130),
    onPrimaryContainer: Color(0xffaff1c4),
    secondary: Color(0xffa8c8ff),
    onSecondary: Color(0xff06305f),
    secondaryContainer: Color(0xff254777),
    onSecondaryContainer: Color(0xffd5e3ff),
    tertiary: Color(0xffd0ca74),
    onTertiary: Color(0xff343200),
    tertiaryContainer: Color(0xff4c4800),
    onTertiaryContainer: Color(0xffece68d),
    error: Color(0xffffb4a7),
    onError: Color(0xff561e16),
    errorContainer: Color(0xff73342a),
    onErrorContainer: Color(0xffffdad4),
    surface: Color(0xff0f1511),
    onSurface: Color(0xffdfe4dd),
    onSurfaceVariant: Color(0xffc0c9c0),
    outline: Color(0xff8a938b),
    outlineVariant: Color(0xff414942),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xffdfe4dd),
    inversePrimary: Color(0xff2b6a46),
    primaryFixed: Color(0xffaff1c4),
    onPrimaryFixed: Color(0xff00210f),
    primaryFixedDim: Color(0xff94d5a9),
    onPrimaryFixedVariant: Color(0xff0d5130),
    secondaryFixed: Color(0xffd5e3ff),
    onSecondaryFixed: Color(0xff001b3c),
    secondaryFixedDim: Color(0xffa8c8ff),
    onSecondaryFixedVariant: Color(0xff254777),
    tertiaryFixed: Color(0xffece68d),
    onTertiaryFixed: Color(0xff1e1c00),
    tertiaryFixedDim: Color(0xffd0ca74),
    onTertiaryFixedVariant: Color(0xff4c4800),
    surfaceDim: Color(0xff0f1511),
    surfaceBright: Color(0xff353b36),
    surfaceContainerLowest: Color(0xff0a0f0c),
    surfaceContainerLow: Color(0xff181d19),
    surfaceContainer: Color(0xff1c211d),
    surfaceContainerHigh: Color(0xff262b27),
    surfaceContainerHighest: Color(0xff313631),
  );

  ThemeData dark() => theme(darkScheme());

  static ColorScheme darkMediumContrastScheme() => const ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xffa9ebbe),
    surfaceTint: Color(0xff94d5a9),
    onPrimary: Color(0xff002c17),
    primaryContainer: Color(0xff5f9e75),
    onPrimaryContainer: Color(0xff000000),
    secondary: Color(0xffccddff),
    onSecondary: Color(0xff00254e),
    secondaryContainer: Color(0xff7292c6),
    onSecondaryContainer: Color(0xff000000),
    tertiary: Color(0xffe6e087),
    onTertiary: Color(0xff292700),
    tertiaryContainer: Color(0xff989344),
    onTertiaryContainer: Color(0xff000000),
    error: Color(0xffffd2cb),
    onError: Color(0xff48140c),
    errorContainer: Color(0xffcc7b6e),
    onErrorContainer: Color(0xff000000),
    surface: Color(0xff0f1511),
    onSurface: Color(0xffffffff),
    onSurfaceVariant: Color(0xffd6dfd5),
    outline: Color(0xffacb4ab),
    outlineVariant: Color(0xff8a928a),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xffdfe4dd),
    inversePrimary: Color(0xff0f5331),
    primaryFixed: Color(0xffaff1c4),
    onPrimaryFixed: Color(0xff001508),
    primaryFixedDim: Color(0xff94d5a9),
    onPrimaryFixedVariant: Color(0xff003f22),
    secondaryFixed: Color(0xffd5e3ff),
    onSecondaryFixed: Color(0xff00112a),
    secondaryFixedDim: Color(0xffa8c8ff),
    onSecondaryFixedVariant: Color(0xff103665),
    tertiaryFixed: Color(0xffece68d),
    onTertiaryFixed: Color(0xff131200),
    tertiaryFixedDim: Color(0xffd0ca74),
    onTertiaryFixedVariant: Color(0xff3a3800),
    surfaceDim: Color(0xff0f1511),
    surfaceBright: Color(0xff404641),
    surfaceContainerLowest: Color(0xff040805),
    surfaceContainerLow: Color(0xff1a1f1b),
    surfaceContainer: Color(0xff242925),
    surfaceContainerHigh: Color(0xff2e342f),
    surfaceContainerHighest: Color(0xff3a3f3a),
  );

  Future<ThemeData> darkMediumContrast() async => theme(darkMediumContrastScheme());

  static ColorScheme darkHighContrastScheme() => const ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xffbdffd1),
    surfaceTint: Color(0xff94d5a9),
    onPrimary: Color(0xff000000),
    primaryContainer: Color(0xff90d1a5),
    onPrimaryContainer: Color(0xff000f05),
    secondary: Color(0xffebf0ff),
    onSecondary: Color(0xff000000),
    secondaryContainer: Color(0xffa4c4fb),
    onSecondaryContainer: Color(0xff000b1f),
    tertiary: Color(0xfffaf399),
    onTertiary: Color(0xff000000),
    tertiaryContainer: Color(0xffccc670),
    onTertiaryContainer: Color(0xff0d0c00),
    error: Color(0xffffece9),
    onError: Color(0xff000000),
    errorContainer: Color(0xffffaea1),
    onErrorContainer: Color(0xff220000),
    surface: Color(0xff0f1511),
    onSurface: Color(0xffffffff),
    onSurfaceVariant: Color(0xffffffff),
    outline: Color(0xffeaf2e9),
    outlineVariant: Color(0xffbcc5bc),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xffdfe4dd),
    inversePrimary: Color(0xff0f5331),
    primaryFixed: Color(0xffaff1c4),
    onPrimaryFixed: Color(0xff000000),
    primaryFixedDim: Color(0xff94d5a9),
    onPrimaryFixedVariant: Color(0xff001508),
    secondaryFixed: Color(0xffd5e3ff),
    onSecondaryFixed: Color(0xff000000),
    secondaryFixedDim: Color(0xffa8c8ff),
    onSecondaryFixedVariant: Color(0xff00112a),
    tertiaryFixed: Color(0xffece68d),
    onTertiaryFixed: Color(0xff000000),
    tertiaryFixedDim: Color(0xffd0ca74),
    onTertiaryFixedVariant: Color(0xff131200),
    surfaceDim: Color(0xff0f1511),
    surfaceBright: Color(0xff4c514c),
    surfaceContainerLowest: Color(0xff000000),
    surfaceContainerLow: Color(0xff1c211d),
    surfaceContainer: Color(0xff2c322d),
    surfaceContainerHigh: Color(0xff373d38),
    surfaceContainerHighest: Color(0xff434843),
  );

  ThemeData darkHighContrast() => theme(darkHighContrastScheme());

  ThemeData theme(ColorScheme colorScheme) => ThemeData(
    useMaterial3: true,
    brightness: colorScheme.brightness,
    colorScheme: colorScheme,
    textTheme: textTheme.apply(bodyColor: colorScheme.onSurface, displayColor: colorScheme.onSurface),
    scaffoldBackgroundColor: colorScheme.surface,
    canvasColor: colorScheme.surface,
    buttonTheme: ButtonThemeData(
      padding: EdgeInsets.all(14),
      shape: RoundedRectangleBorder(borderRadius: BorderRadiusGeometry.circular(14)),
    ),
    inputDecorationTheme: InputDecorationTheme(
      border: OutlineInputBorder(borderRadius: BorderRadius.circular(14)),
    ),
  );
}
