spring.application.name=FluentApiGateway

# File Upload Configuration
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
spring.servlet.multipart.enabled=true

# Server
server.port=${API_GATEWAY_PORT:8000}

# Microservice URLs
processing.urls.orchestrator=${PROCESSING_ORCHESTRATOR_URL:http://localhost:8013}
analysis.urls.orchestrator=${ANALYSIS_ORCHESTRATOR_URL:http://localhost:8011}
